# Site settings
author: Joe Ganobsik
title: DevOps to Dev
header-img: img/home-bg.png
email: jganobsik@gmail.com
copyright_name: Joe Ganobsik
description: > # this means to ignore newlines until "baseurl:"
  My journey into Software Engineering as a former Systems Administrator
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jganobsik

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
